### ISSUE TITLE
How to set minemagic with old version in Rails 6?

### ISSUE THREAD

**Issue by patrick204nqh** [minad/mimemagic#145]
Run **rails server/rails console**
```
/home/patrick/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- mimemagic/overlay (LoadError)
    from /home/patrick/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
    from /home/patrick/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
    from /home/patrick/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
    from /home/patrick/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
    from /home/patrick/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `block in require'
    from /home/patrick/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency'
    from /home/patrick/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require'
 ...
```

#### mimemagic was removed, so how to set old version?, please!

**Comment by patrick204nqh** [comment]
sorry, I have resolved.
