### ISSUE TITLE
cannot load such file -- mimemagic/path

### ISSUE THREAD

**Issue by shan-shaji** [minad/mimemagic#171]
Getting this error when running a rake task.

```
LoadError: cannot load such file -- mimemagic/path
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:332:in `block in require'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:332:in `require'
/Library/Ruby/Gems/2.6.0/gems/mimemagic-0.3.10/lib/mimemagic/tables.rb:5:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:332:in `block in require'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:332:in `require'
/Library/Ruby/Gems/2.6.0/gems/mimemagic-0.3.10/lib/mimemagic.rb:3:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/runtime.rb:55:in `each'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/runtime.rb:55:in `block in require'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/runtime.rb:44:in `each'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/runtime.rb:44:in `require'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler.rb:195:in `require'
/Users/sshaji2/Documents/turbo/config/application.rb:26:in `<top (required)>'
/Users/sshaji2/Documents/turbo/Rakefile:4:in `require'
/Users/sshaji2/Documents/turbo/Rakefile:4:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/cli/exec.rb:58:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/cli/exec.rb:23:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/cli.rb:492:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/cli.rb:34:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/cli.rb:28:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/exe/bundle:45:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.4.8/exe/bundle:33:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

**Comment by entp** [comment]
You need to actually build the gem, using the rake task and having freedesktop installed on the local system. Or downgrade to 0.3.6.
